-- 코드를 입력하세요
SELECT ri.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO ri
JOIN REST_REVIEW rr ON rr.REST_ID = ri.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY rr.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;